"""Melody height over time (a pitch contour) for a stretch of a song, to drive animation: a camera that climbs with a
solo, shapes that rise with the notes.

    python tools/audio/pitch.py assets/song.mp3 --range 104.14:132.03 --js src/scenes/<video>/solo_pitch.js --name SOLO
        [--fmin 150] [--fmax 1500] [--highpass 180] [--fps 24]

Writes `const NAME = { t0, fps, midi: [...] }`: one MIDI note number per frame from t0 (null where nothing is pitched),
median-smoothed over ±50 ms. Prints a per-bar summary if --beats (beats.py JSON) is given.

Pitfall this handles: on a full mix, pyin locks onto the loudest pitched line, which is usually the BASS (here it
reported MIDI ~40, E2, for a sax solo). High-passing the mix and raising fmin moves it onto the lead line. It still
can't separate instruments: check the contour against your ears (or the person's) before trusting a bar.
"""
import argparse, json, os
import numpy as np
import librosa, scipy.signal as ss

ap = argparse.ArgumentParser()
ap.add_argument('audio')
ap.add_argument('--range', required=True, help='a:b seconds')
ap.add_argument('--js', default=None); ap.add_argument('--json', default=None); ap.add_argument('--name', default='PITCH')
ap.add_argument('--fmin', type=float, default=150); ap.add_argument('--fmax', type=float, default=1500)
ap.add_argument('--highpass', type=float, default=180); ap.add_argument('--fps', type=int, default=24)
ap.add_argument('--beats', default=None)
a = ap.parse_args()

t0, t1 = map(float, a.range.split(':'))
sr, hop = 22050, 256
y, _ = librosa.load(a.audio, sr=sr, mono=True, offset=max(0, t0 - .5), duration=t1 - t0 + 1)
pad = min(.5, t0)
b, c = ss.butter(4, a.highpass / (sr / 2), 'high'); y = ss.filtfilt(b, c, y)
yh, _ = librosa.effects.hpss(y, margin=2.0)
f0, voiced, _ = librosa.pyin(yh, fmin=a.fmin, fmax=a.fmax, sr=sr, frame_length=2048, hop_length=hop)
tt = np.arange(len(f0)) * hop / sr + t0 - pad
m = librosa.hz_to_midi(f0)
ok = voiced & ~np.isnan(m)
out = []
for x in np.arange(t0, t1, 1 / a.fps):
    w = ok & (tt >= x - .05) & (tt < x + .05)
    out.append(round(float(np.median(m[w])), 2) if w.any() else None)
v = [q for q in out if q is not None]
print(f'{len(out)} frames, {len(v)} pitched; MIDI p5 {np.percentile(v, 5):.1f}, median {np.median(v):.1f}, p95 {np.percentile(v, 95):.1f}')

if a.beats:
    B = json.load(open(a.beats))
    for bar in B['bars']:
        if bar['end'] <= t0 or bar['t'] >= t1: continue
        q = [out[i] for i in range(len(out)) if out[i] is not None and bar['t'] <= t0 + i / a.fps < bar['end']]
        if q: print(f"  bar {bar['bar']:4d}  {bar['t']:7.2f}s  median {np.median(q):5.1f}  max {max(q):5.1f}")

data = {'t0': round(t0, 3), 'fps': a.fps, 'midi': out}
if a.json:
    os.makedirs(os.path.dirname(a.json), exist_ok=True); json.dump(data, open(a.json, 'w'))
if a.js:
    os.makedirs(os.path.dirname(a.js), exist_ok=True)
    with open(a.js, 'w') as f:
        f.write(f'// pitch contour generated by tools/audio/pitch.py from {os.path.basename(a.audio)} ({t0}–{t1} s): MIDI note per frame.\n')
        f.write(f"const {a.name} = {{ t0: {t0}, fps: {a.fps}, midi: [{','.join('null' if q is None else f'{q:.1f}' for q in out)}] }};\n")
    print('wrote', a.js)
